// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjhVxx1xsunE3d2T7Q62ibmrv7t1umBU',
    appId: '1:537217854274:android:30c0cc953135bd0fab36db',
    messagingSenderId: '537217854274',
    projectId: 'personal-finance-app-dbf75',
    storageBucket: 'personal-finance-app-dbf75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbxImxQOACd8Z7XRayUd1NQlHTjbHhRlw',
    appId: '1:537217854274:ios:7e07f44bf960e52fab36db',
    messagingSenderId: '537217854274',
    projectId: 'personal-finance-app-dbf75',
    storageBucket: 'personal-finance-app-dbf75.firebasestorage.app',
    iosBundleId: 'com.app.finances',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcXA9mNKWZ8TZ9N4Mj2ovlC8HGzdJZKYs',
    appId: '1:537217854274:web:c65c721807fa9e0fab36db',
    messagingSenderId: '537217854274',
    projectId: 'personal-finance-app-dbf75',
    authDomain: 'personal-finance-app-dbf75.firebaseapp.com',
    storageBucket: 'personal-finance-app-dbf75.firebasestorage.app',
  );
}
